# Generated by Django 4.2.16 on 2026-09-20 16:21

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banners/', validators=[core.validators.validate_image_file])),
                ('link_target', models.CharField(blank=True, help_text='Deep link / screen name / URL', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('target_type', models.CharField(choices=[('ALL', 'All customers'), ('PROJECT', 'A project'), ('SELECTED', 'Selected customers')], default='ALL', max_length=20)),
                ('channel', models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email'), ('BOTH', 'Push + Email')], default='BOTH', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent')], default='DRAFT', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_customers', models.ManyToManyField(blank=True, related_name='campaigns', to='accounts.customer')),
                ('target_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notif_type', models.CharField(choices=[('KYC_APPROVED', 'KYC approved'), ('KYC_REJECTED', 'KYC rejected'), ('PAYMENT_PROOF_SUBMITTED', 'Payment proof submitted'), ('PAYMENT_APPROVED', 'Payment approved'), ('PAYMENT_REJECTED', 'Payment rejected'), ('RECEIPT_ISSUED', 'Receipt issued'), ('DOCUMENT_UPLOADED', 'Document uploaded'), ('PAYMENT_DUE_REMINDER', 'Payment due reminder'), ('TICKET_REPLY', 'Ticket reply'), ('MILESTONE_CHANGE_APPROVED', 'Milestone change approved'), ('MILESTONE_CHANGE_DECLINED', 'Milestone change declined'), ('MILESTONE_CHANGE_COUNTERED', 'Milestone change countered'), ('ANNOUNCEMENT', 'Announcement'), ('BANNER', 'New banner')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('deep_link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
