# Generated by Django 4.2.16 on 2026-10-07 21:42

from django.db import migrations, models


def scheduled_to_draft(apps, schema_editor):
    """Scheduling is gone; anything still waiting to be scheduled goes back to draft (nothing ever sent them)."""
    NotificationCampaign = apps.get_model('notifications', 'NotificationCampaign')
    NotificationCampaign.objects.filter(status='SCHEDULED').update(status='DRAFT')


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(scheduled_to_draft, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='scheduled_at',
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent')], default='DRAFT', max_length=20),
        ),
    ]
