# Generated by Django 4.2.16 on 2026-09-20 16:21

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot_number', models.CharField(max_length=50)),
                ('size', models.CharField(help_text='e.g. 1200 sq.ft', max_length=50)),
                ('block_sector', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='List price', max_digits=14)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_paid_outside_app', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('instalment_count', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['project__name', 'plot_number'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='e.g. ["Clubhouse", "24x7 security"]')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='projects/brochures/', validators=[core.validators.validate_document_file])),
                ('development_status', models.CharField(choices=[('PLANNING', 'Planning'), ('UNDER_CONSTRUCTION', 'Under construction'), ('READY', 'Ready'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=30)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/images/', validators=[core.validators.validate_image_file])),
                ('image_type', models.CharField(choices=[('LAYOUT', 'Layout / site plan'), ('GALLERY', 'Gallery')], default='GALLERY', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlotAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('TRANSFERRED', 'Transferred')], max_length=20)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='projects.plot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='plot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('project', 'plot_number')},
        ),
    ]
