# Generated by Django 4.2.16 on 2026-09-20 16:21

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot_confirmed', models.BooleanField(default=False)),
                ('plot_mismatch_note', models.TextField(blank=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='kyc/receipts/', validators=[core.validators.validate_receipt_file])),
                ('receipt_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('receipt_payment_date', models.DateField(blank=True, null=True)),
                ('step2_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('step2_rejection_reason', models.TextField(blank=True)),
                ('step2_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='kyc/videos/', validators=[core.validators.validate_video_file])),
                ('prompt_lines', models.JSONField(blank=True, default=list)),
                ('step3_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('step3_rejection_reason', models.TextField(blank=True)),
                ('step3_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to='accounts.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.CharField(choices=[('STEP2', 'Step 2'), ('STEP3', 'Step 3')], max_length=10)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='kyc.kycsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
